services:
  - type: worker
    name: telegram.auto
    env: docker
    repo: https://github.com/rrsign/telegr.auto
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: URL
        sync: false